name: Acesso Diário ao Site

on:
  schedule:
    - cron: '0 13 * * *'  # Roda às 10h (Brasília)
  workflow_dispatch:  # Para rodar manualmente também

jobs:
  acesso:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y chromium-browser
          pip install selenium

          # Instalar ChromeDriver compatível
          CHROME_VERSION=$(chromium-browser --version | grep -oP "\d+\.\d+\.\d+")
          echo "Instalando ChromeDriver para versão $CHROME_VERSION"
          wget -q -O chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Executar script
        run: python acesso.py
