name: Acesso Diário ao Site

on:
  schedule:
    - cron: '0 13 * * *'  # Roda diariamente às 10h (Brasília)
  workflow_dispatch:

jobs:
  acesso:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest  # tudo pronto aqui

    steps:
      - name: Instalar Python e Selenium
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
          pip install selenium

      - name: Rodar script
        run: |
          echo "from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from time import sleep

options = Options()
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')

driver = webdriver.Chrome(options=options)
driver.get('https://google.com')
print('Página carregada com sucesso.')
sleep(5)
driver.quit()" > acesso.py

          python3 acesso.py
